defaults:
  - optional tp_overlap@model.ub_tp_comm_overlap_cfg:

trainer:
  # these args are respected
  num_nodes: 8
  devices: 8
  accelerator: gpu
  precision: bf16

  ppo:
    max_steps: -1  # max PPO steps (-1 to go through the whole train set)
    val_check_interval: 10 
    save_interval: ${.val_check_interval}
    gradient_clip_val: 1.0

    # PPO args to generate the data for training
    initial_policy_kl_penalty: 0.01
    use_absolute_kl: True
    discount_factor: 1.0
    gae_lambda: 0.95
    normalize_advantages: True

    # pick up from the model
    # *do not change this*
    max_epochs: 1 # anything above 1 not supported
    model_gbs: ${model.global_batch_size}
    model_mbs: ${model.micro_batch_size}

    # the sequence length to pad the rollout batch to
    # this reduces fragmentation at the cost of using more
    # memory, set to null if we don't want to pad it
    # to a constant size
    rollout_batch_seq_length: null

  # no need to change these
  logger: False # logger provided by exp_manager
  enable_checkpointing: False
  use_distributed_sampler: False
  max_time: null
  max_epochs: ${.ppo.max_epochs}
  max_steps: ${.ppo.max_steps}

remote_critic_rm:
  # what to batch the inputs to
  # set to None if no batching when sending inference to the critic
  pad_to_length: ${model.encoder_seq_length}

  # must match the same flag in the critic config
  combine_rm_and_critic_server: True

  # reward model server, specify if 
  # combine_rm_and_critic server is False
  reward_model:
    name: reward_model
    ip: localhost
    port: 5555

  critic:
    name: 
      train: critic_train
      infer: critic_infer
      save: critic_save
    ip: localhost
    port: 5556


exp_manager:
  explicit_log_dir: /results
  exp_dir: null
  name: megatron_gpt_ppo_actor
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: nemo_aligner_ppo
    name: gpt3_ppo_2b
  resume_from_checkpoint: null # The path to a checkpoint file to continue the training, restores the whole state including the epoch, step, LR schedulers, apex, etc.
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_global_rewards
    save_top_k: 1
    mode: max
    always_save_nemo: False # saves nemo file during validation, not implemented for model parallel
    save_nemo_on_train_end: True # not recommended when training large models on clusters with short time limits
    filename: 'megatron_gpt-{step}-{consumed_samples}-{ppo_optimization_step}-{epoch}-{val_global_rewards:.3f}'
    model_parallel_size: ${multiply:${model.tensor_model_parallel_size}, ${model.pipeline_model_parallel_size}}

pretrained_checkpoint:
  restore_from_path: null

model:

  ppo:
    # training generation mbs
    rollout_micro_batch_size: 8
    num_rollout_samples: 512

    # mbs to do log prob inference, can be set to
    # lower than rollout_micro_batch_size to reduce
    # memory usage
    forward_micro_batch_size: ${.rollout_micro_batch_size}

    # val generation mbs
    val_rollout_micro_batch_size: ${.rollout_micro_batch_size}
    num_val_samples: ${.num_rollout_samples}

    # to offload during generation or not
    offload_adam_states: True

    # PPO loss params
    entropy_bonus: 0.0
    ratio_eps: 0.2

    # params for generation
    sampling_params:
      use_greedy: False
      temperature: 1.0
      top_k: 0
      top_p: 1.0
      repetition_penalty: 1.0
      add_BOS: False
      all_probs: False
      compute_logprob: False
      # will be used in NeMo version > 1.20.0
      # keeping it for now
      end_strings: ["<|endoftext|>", "<extra_id_1>"]

    # length argument for autoregressive sampling
    # max length means max amount of tokens to generate
    length_params:
      max_length: ${int_div:${model.encoder_seq_length}, 2}
      min_length: 1

  mcore_gpt: True
  # these control the mbs/gbs during PPO training
  micro_batch_size: 1
  global_batch_size: 64
  megatron_amp_O2: True

  encoder_seq_length: 4096
  max_position_embeddings: ${model.encoder_seq_length}

  ## Sequence Parallelism
  sequence_parallel: False

  # miscellaneous
  seed: 1234
  
  optim:
    name: distributed_fused_adam
    bucket_cap_mb: 200
    overlap_grad_sync: False
    contiguous_grad_buffer: True
    lr: 9e-7
    weight_decay: 0.1 
    betas: 
    - 0.9
    - 0.98
    sched:
      name: CosineAnnealing
      warmup_steps: 10
      constant_steps: 1000
      min_lr: 9e-8

  precision: ${trainer.precision}

  data:
    data_impl: mmap
    splits_string: null
    seq_length: ${model.encoder_seq_length}
    skip_warmup: True
    num_workers: 2
    dataloader_type: single # cyclic
    reset_position_ids: False # Reset position ids after end-of-document token
    reset_attention_mask: False # Reset attention mask after end-of-document token
    eod_mask_loss: False # Mask loss for the end of document tokens
    index_mapping_dir: null # path to save index mapping .npy files, by default will save in the same location as data_prefix
    data_prefix: null
