#!/bin/bash

# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

set -eoux pipefail

export PRETRAINED_CHECKPOINT_NEMO_FILE=${ALIGNER_CI_DIR}/checkpoints/tiny-llama3-results-nlayers2-hidden128-ffn448-nhead4-qgroup2-megatron_gpt.nemo
bash ../dpo.sh \
  ++model.optim.name=mcore_distributed_optim \
  ++model.context_parallel_size=1 \
  2>&1 | tee $(basename $0)-cp1.log

bash ../dpo.sh \
  ++model.optim.name=mcore_distributed_optim \
  ++model.context_parallel_size=2 \
  2>&1 | tee $(basename $0)-cp2.log

final_cp1_loss=$( grep -o -P 'train_loss.{0,5}' $( basename $0 )-cp1.log | tail -n 1 | tail -c 4 )
final_cp2_loss=$( grep -o -P 'train_loss.{0,5}' $( basename $0 )-cp2.log | tail -n 1 | tail -c 4 )

if [ $final_cp1_loss != $final_cp2_loss ]; then
    echo "Assertion failed: $final_cp1_loss does not equal $final_cp2_loss" >&2
  exit 1
fi
exit 0
