# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Build NeMo Aligner container
on: 
  workflow_call:
    inputs:
      ref: 
        description: Git ref to checkout
        default: ${{ github.event.pull_request.head.sha || github.sha }}
        required: false
        type: string

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

env:
  TRTLLM_VERSION: v0.10.0
  TE_TAG: 7d576ed25266a17a7b651f2c12e8498f67e0baea
  ALIGNER_COMMIT: ${{ inputs.ref }}

jobs:
  main:
    runs-on: self-hosted-azure-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
          ref: ${{ env.ALIGNER_COMMIT }}

      - name: Clean runner cache
        run: | 
          docker system prune --filter "until=24h" --force
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          # We use `docker` driver as this speeds things up for 
          # trivial (non-multi-stage) builds.
          driver: docker-container

      - name: Set cache-to
        id: cache-to
        run: |
          CACHE="nemoci.azurecr.io/nemo_aligner_container_cache:${{ github.event.pull_request.number || 'noop' }}"

          if [[ "${{ github.ref }}" == "refs/head/main" ]]; then
            CACHE=$(eche -E "$CACHE\nnemoci.azurecr.io/nemo_aligner_container_cache:main")
          fi

          echo "$CACHE"

          echo "CACHE<<EOF" >> $GITHUB_ENV
          echo "$CACHE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Build and push TRTLLM
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          target: trtllm-build
          build-args: 
            MAX_JOBS=32
            ALIGNER_COMMIT=${{ env.ALIGNER_COMMIT }}
            TRTLLM_VERSION=${{ env.TRTLLM_VERSION }}
          cache-from: nemoci.azurecr.io/nemo_aligner_container_trtllm_build_cache:${{ env.TRTLLM_VERSION }}
          cache-to: nemoci.azurecr.io/nemo_aligner_container_trtllm_build_cache:${{ env.TRTLLM_VERSION }}
          tags: nemoci.azurecr.io/nemo_aligner_container_trtllm_build:${{ env.TRTLLM_VERSION }}

      - name: Build and push TE
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          target: te-build
          build-args: 
            MAX_JOBS=32
            ALIGNER_COMMIT=${{ env.ALIGNER_COMMIT }}
            TE_TAG=${{ env.TE_TAG }}
          cache-from: nemoci.azurecr.io/nemo_aligner_container_te_build_cache:${{ env.TRTLLM_VERSION }}
          cache-to: nemoci.azurecr.io/nemo_aligner_container_te_build_cache:${{ env.TRTLLM_VERSION }}
          tags: nemoci.azurecr.io/nemo_aligner_container_te_build:${{ env.TE_TAG }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: true
          target: final
          build-args: |
            MAX_JOBS=32
            ALIGNER_COMMIT=${{ env.ALIGNER_COMMIT }}
            TRTLLM_VERSION=${{ env.TRTLLM_VERSION }}
            TE_TAG=${{ env.TE_TAG }}
          cache-from: |
            nemoci.azurecr.io/nemo_aligner_container_cache:${{ github.event.pull_request.number || 'noop' }}
            nemoci.azurecr.io/nemo_aligner_container_cache:main
          cache-to: ${{ env.CACHE }}
          tags: nemoci.azurecr.io/nemo_aligner_container:${{ github.run_id }}