# Regularly updates the CI container
name: Bump Bot
on:
  workflow_dispatch:
  pull_request:
    
  schedule:
    - cron: 0 0 * * *

jobs:
  bump-mcore:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_bump_dockerfile.yml@ko3n1g/feat/bump-dockerfile
    with:
      source-repository: NVIDIA/Megatron-LM
      source-ref: main
      build-arg: MLM_TAG
      dockerfile: Dockerfile
      base-branch: dev
      cicd-label: Run CICD
      pr-reviewers: 'terrykong'
    secrets:
      PAT: ${{ secrets.PAT }}
  