name: "Code freeze"

on:
  workflow_dispatch:
    inputs:
      type_of_release:
        type: choice
        description: Type of release
        options: 
        - major
        - minor
        - pre_release

jobs:
  code-freeze:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_code_freeze.yml@v0.1.0
    with:
      name_of_library: NeMo-Aligner
      type_of_release: ${{ inputs.type_of_release }}
      python_package: nemo_aligner
    secrets:
      SLACK_RELEASE_ENDPOINT: ${{ secrets.SLACK_RELEASE_ENDPOINT }}