name: "Code freeze"

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Type of release
        options: 
        - major
        - minor
      freeze-commit:
        type: string
        description: Commit SHA to use for cut-off
        required: false
        default: main
jobs:
  code-freeze:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_code_freeze.yml@v0.21.6
    with:
      library-name: NeMo-Aligner
      python-package: nemo_aligner
      release-type: ${{ inputs.release-type }}
      freeze-commit: ${{ inputs.freeze-commit }}
    secrets:
      SLACK_RELEASE_ENDPOINT: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
      SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
