name: "Code freeze"

on:
  workflow_dispatch:
    inputs:
      type_of_release:
        type: choice
        description: Type of release
        options: 
        - major
        - minor
        - pre_release
      mcore_version:
        description: 'Version of MCore to use (must be a valid git ref)'
        required: true
        type: string

jobs:
  code-freeze:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_code_freeze.yml
    with:
      name_of_library: NeMo-Aligner
      type_of_release: ${{ inputs.type_of_release }}
      python_package: nemo_aligner
    secrets:
      SLACK_RELEASE_ENDPOINT: ${{ secrets.SLACK_RELEASE_ENDPOINT }}