name: sync main with dev
on:
  push:
    branches:
      - main
  pull_request:
    

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

jobs:
  sync-branches-via-rebase:
    runs-on: ubuntu-latest
    name: syncing main with dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ko3n1g/dev

      - name: Attempt rebase
        run: |
          git fetch origin main
          git rebase origin/main
          